// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB15wK2h6sdf9-7BNyYIr0GN6bUfKBZ3ls',
    appId: '1:733948521520:web:8950e3860267a5dab7d1f5',
    messagingSenderId: '733948521520',
    projectId: 'crypflup',
    authDomain: 'crypflup.firebaseapp.com',
    storageBucket: 'crypflup.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAElHvlBPerH4ePIAeF6UwLSBcxMp6Qrbk',
    appId: '1:733948521520:android:e50df08c2d89b86db7d1f5',
    messagingSenderId: '733948521520',
    projectId: 'crypflup',
    storageBucket: 'crypflup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRHn4YRcRmz2d3Hfj9z3DJz4oXdWzx1DE',
    appId: '1:733948521520:ios:a21d396b3f0fca1bb7d1f5',
    messagingSenderId: '733948521520',
    projectId: 'crypflup',
    storageBucket: 'crypflup.appspot.com',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRHn4YRcRmz2d3Hfj9z3DJz4oXdWzx1DE',
    appId: '1:733948521520:ios:96103c4c2dbc57f8b7d1f5',
    messagingSenderId: '733948521520',
    projectId: 'crypflup',
    storageBucket: 'crypflup.appspot.com',
    iosBundleId: 'com.example.cry.RunnerTests',
  );
}
